### ISSUE TITLE
Booksonic doesn't respect X-Forwarded-Proto

### ISSUE THREAD

**Issue by ghost** [linuxserver/docker-booksonic#10]
The linuxserver/airsonic images deliver mixed content unless passed the header `X-Forwarded-Proto https` and `server.use-forward-headers=true` placed in `airsonic.properties`.

Even when configured with these two options, Booksonic still delivers mixed content.

**Comment by tobbenb** [comment]
Isn't this something that should be dealt with by the booksonic developers?

**Comment by ghost** [comment]
> Isn't this something that should be dealt with by the booksonic developers?

My understanding is that this is an internal change that can be done to the existing image. See https://github.com/airsonic/airsonic/issues/594

**Comment by thelamer** [comment]
As we do provide the `/config/booksonic.properties` file for modification where you can add these values and this file is automatically generated by their application. You have the ability to do this. 
If this truly is a completely unobtrusive change to the application for users not leveraging a proxy then I would recommend you ask for this to be added as a default behavior upstream.

**Comment by ghost** [comment]
> As we do provide the `/config/booksonic.properties` file for modification where you can add these values and this file is automatically generated by their application. You have the ability to do this.
> If this truly is a completely unobtrusive change to the application for users not leveraging a proxy then I would recommend you ask for this to be added as a default behavior upstream.

Again, I have done these changes but only the Airsonic image supports them, not Booksonic, so the bug remains but :man_shrugging: you do you.

**Comment by thelamer** [comment]
Then I misunderstood the issue, this needs to 100% be reported upstream. We do not have control over the Java webserver , this rests on the application war we are running.
