### ISSUE TITLE
Can't find the scan button in settings

### ISSUE THREAD

**Issue by pochacho99** [linuxserver/docker-booksonic#20]
Using the latest docker image. I can't find the Scan media button in settings anymore? When i go to settings, I can only see Personal Settings and Password, Players, Shared Media etc.

**Comment by CHBMB** [comment]
Please open a new issue with the template completed.  If we can't attempt to reproduce it then we don't have enough manpower to look at vague issues.

I can't reproduce on x64 at least.

https://i.imgur.com/7xLXJnh.png
