### ISSUE TITLE
Not seeing full Settings option in Settings page

### ISSUE THREAD

**Issue by pochacho99** [linuxserver/docker-booksonic#21]
## Expected Behavior
See Full settings options including Scan Media Folders when enter Settings page.

## Current Behavior
Only seeing abbreviated settings, no Scan Media Folders found in any tab. Using Chrome browser, but is is the same behavior from any browser.
![Booksonic settings](https://user-images.githubusercontent.com/39760089/75848481-50bf5380-5e1d-11ea-88b7-b2da5263efc0.png)

## Steps to Reproduce
1. Click on Settings from Left Hand Menu

## Environment
**OS: Synology NAS
**CPU architecture:** x86_64 
**How docker service was installed:**      
Docker was installed through Synology NAS docker GUI

## Command used to create docker container (run/create/compose/screenshot)
![Docker settings](https://user-images.githubusercontent.com/39760089/75848728-f2df3b80-5e1d-11ea-974b-a63d1912454f.png)

## Docker logs
[Booksonic Logs.txt](https://github.com/linuxserver/docker-booksonic/files/4285258/Booksonic.Logs.txt)

**Comment by CHBMB** [comment]
You're not logged in as an admin user.
