### ISSUE TITLE
Last Version is broken

### ISSUE THREAD

**Issue by Moppen72** [linuxserver/docker-booksonic#26]
Hello,

I really don't know how to use this. I am Sorry, but I just wanted to draw your attention to the last release of the container which seems to be "broken".

Regards,
Stefan

**Comment by dontoverthinkit** [comment]
@aptalca - not sure who to notify but the issue template linked above is currently returning a 404.
@Moppen72 - #25 gives a good example of info to provide for next time :) (and happens to be an issues raised for the same problem so this one can probably be closed / linked to #25 as a duplicate.

Kind regards,
Del

**Comment by j0nnymoe** [comment]
closing in favour of #25
