### ISSUE TITLE
Booksonic Air released

### ISSUE THREAD

**Issue by popeen** [linuxserver/docker-booksonic#28]
Hi, Booksonic dev here.

Just wanted to let you know that Booksonic Air has been released and is now the recommended server from my side.
See https://github.com/popeen/Booksonic-Air

Booksonic works just like Airsonic (meaning it has embeded tomcat) and you should be able to resuse the code from https://github.com/linuxserver/docker-airsonic

**Comment by CHBMB** [comment]
Awesome @popeen, is it a drop in replacement for the existing booksonic?  As in, would the upgrade process be seamless if we pushed booksonic-air to the current repository, or would we be better to create a new repository called `booksonic-air`?

**Comment by popeen** [comment]
Not fully drop in no. It can be made that way by renaming a few files but considering the older server was based on a quite old version of Subsonic I wouldn't trust that not to lead to any weird bugs so a new repo might be a good idea.

**Comment by CHBMB** [comment]
Just testing this locally.

https://github.com/linuxserver/docker-booksonic-air/tree/Initial-Bionic

**Comment by ironicbadger** [comment]
In the original Booksonic container `CONTEXT_PATH` was used to set the reverse proxy `base-url` setting. However, bs-air doesn't have a similar `booksonic.properties` file instead it creates `airsonic.properties` which is not really human-readable.

Container builds fine, app runs fine on `localhost:4040` but at present it won't work with reverse proxies that I can find...

I have opened an issue upstream to track this but it's a vital flag for LSIO users.

https://github.com/popeen/Booksonic-Air/issues/19

**Comment by CHBMB** [comment]
Took a look at this, looking at the booksonic-air repository here:

https://github.com/popeen/Booksonic-Air/blob/c5bcc2c97140c19dcddba0f23db37687f06b8a0e/contrib/airsonic.service#L18

and reflecting that in the `run` file I think resolves this issue.

https://github.com/linuxserver/docker-booksonic-air/commit/1667c2534bad5d35c0c0bbeda068bffa77d83c35

Testing locally seems to work.

**Comment by ironicbadger** [comment]
@CHBMB 👍 just tested and works as expected. Tested with SWAG and Traefik.

**Comment by GitJamz** [comment]
hey guys..
May one be as bold and ask when this might be released by linuxserver? I just found out about this project and need to either decide to wait for a release or go with something else depending on how much the waiting time is.
thanks

**Comment by CHBMB** [comment]
@GitJamz I'm just adding it to the pipeline now, needs a review from one of the other team members then it should be within the next 24 hours, probably sooner.

In so far as "something else" there's not really much else available on the audiobook front afaik, there's booksonic, but dev has stopped on that as booksonic-air is the successor.

**Comment by GitJamz** [comment]
> @GitJamz I'm just adding it to the pipeline now, needs a review from one of the other team members then it should be within the next 24 hours, probably sooner.
> 
> In so far as "something else" there's not really much else available on the audiobook front afaik, there's booksonic, but dev has stopped on that as booksonic-air is the successor.

boink boink.. Nice.. Within 24hours! I was afraid you were gonna say weeks!
Good job boys and gals! Lets hope for release soon.

**Comment by CHBMB** [comment]
Closed with https://github.com/linuxserver/docker-booksonic-air/pull/2
