### ISSUE TITLE
Mark the image as deprecated

### ISSUE THREAD

**Issue by frollo** [linuxserver/docker-booksonic#30]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

As stated by the dev in #28 this version of the software has been deprecated. The image should reflect it in order to avoid misleading users. 
------------------------------

## Desired Behavior

It should be clear to new Booksonic users that they are expected to use Booksonic Air
## Current Behavior

Both images are presented as if they are two different softwares and there aren't legacy versions. The current software version has some troubles with podcasts and media recognition and does not work with the app. 
## Alternatives Considered

Renaming the image to something like `booksonic-legacy` or removing it altogether will solve the issue all the same, but might end up breaking some users' setups. The same goes for merging the two images (as stated by the dev in #28)

**Comment by nemchik** [comment]
We've recently implemented a new deprecation option in our build system. I've opened #31 with this option enabled. Once it merges we should see this image noted as deprecated.
