### ISSUE TITLE
Update 92 breaks booksonic

### ISSUE THREAD

**Issue by zerodogg** [linuxserver/docker-booksonic#4]
After updating to the latest build of the image (92), the container no longer works. See the log output below. I tried manually removing the lockfile, but it makes no difference. Reverting to image 91 fixes the issue.

My host is Debian 9 x86_64 with docker 18.03.1-ce.

docker logs:

    2018-06-23 07:53:22.792:INFO:/:main: Initializing Spring root WebApplicationContext
    [2018-06-23 07:53:23,944] WARN  org.springframework.beans.factory.support.DisposableBeanAdapter - Invocation of destroy method 'shutdown' failed on bean with name 'cxf': org.
    springframework.beans.factory.BeanCreationNotAllowedException: Error creating bean with name 'ajaxTagServiceSecure': Singleton bean creation not allowed while the singletons
    of this factory are in destruction (Do not request a bean from a BeanFactory in a destroy method implementation!)
    [2018-06-23 07:53:23,945] ERROR org.springframework.web.context.ContextLoader - Context initialization failed
    org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'mediaFileService' defined in ServletContext resource [/WEB-INF/applicationContext-serv
    ice.xml]: Cannot resolve reference to bean 'metaDataParserFactory' while setting bean property 'metaDataParserFactory'; nested exception is org.springframework.beans.factory.
    BeanCreationException: Error creating bean with name 'metaDataParserFactory' defined in ServletContext resource [/WEB-INF/applicationContext-service.xml]: Cannot create inner
     bean 'net.sourceforge.subsonic.service.metadata.FFmpegParser#23f7d05d' of type [net.sourceforge.subsonic.service.metadata.FFmpegParser] while setting bean property 'parsers'
     with key [1]; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'net.sourceforge.subsonic.service.metadata.FFmpegPar
    ser#23f7d05d' defined in ServletContext resource [/WEB-INF/applicationContext-service.xml]: Cannot resolve reference to bean 'transcodingService' while setting bean property
    'transcodingService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'transcodingService' defined in ServletContex
    t resource [/WEB-INF/applicationContext-service.xml]: Cannot resolve reference to bean 'playerService' while setting bean property 'playerService'; nested exception is org.sp
    ringframework.beans.factory.BeanCreationException: Error creating bean with name 'playerService' defined in ServletContext resource [/WEB-INF/applicationContext-service.xml]:
     Invocation of init method failed; nested exception is org.springframework.jdbc.CannotGetJdbcConnectionException: Could not get JDBC Connection; nested exception is java.sql.
    SQLException: The database is already in use by another process: org.hsqldb.persist.NIOLockFile@a03e1507[file =/config/db/booksonic.lck, exists=true, locked=false, valid=fals
    e, fl =null]: java.lang.Exception: checkHeartbeat(): lock file [/config/db/booksonic.lck] is presumably locked by another process.
    Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'metaDataParserFactory' defined in ServletContext resource [/WEB-INF/applica
    tionContext-service.xml]: Cannot create inner bean 'net.sourceforge.subsonic.service.metadata.FFmpegParser#23f7d05d' of type [net.sourceforge.subsonic.service.metadata.FFmpeg
    Parser] while setting bean property 'parsers' with key [1]; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'net.so
    urceforge.subsonic.service.metadata.FFmpegParser#23f7d05d' defined in ServletContext resource [/WEB-INF/applicationContext-service.xml]: Cannot resolve reference to bean 'tra
    nscodingService' while setting bean property 'transcodingService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name
    'transcodingService' defined in ServletContext resource [/WEB-INF/applicationContext-service.xml]: Cannot resolve reference to bean 'playerService' while setting bean propert
    y 'playerService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'playerService' defined in ServletContext resour
    ce [/WEB-INF/applicationContext-service.xml]: Invocation of init method failed; nested exception is org.springframework.jdbc.CannotGetJdbcConnectionException: Could not get J
    DBC Connection; nested exception is java.sql.SQLException: The database is already in use by another process: org.hsqldb.persist.NIOLockFile@a03e1507[file =/config/db/bookson
    ic.lck, exists=true, locked=false, valid=false, fl =null]: java.lang.Exception: checkHeartbeat(): lock file [/config/db/booksonic.lck] is presumably locked by another process
    .

**Comment by zerodogg** [comment]
Still broken in 93.

**Comment by CHBMB** [comment]
Can't reproduce that here I'm afraid.  Been using booksonic since we released it and never had an issue.  What's your docker run command?

**Comment by zerodogg** [comment]
Hrm, not really sure what was wrong with the container. Removing the container, and removing all images of linuxserver/booksonic and then re-adding the container (with the exact same settings), fixed it.
